pipeline {
    agent any

    tools {
        // Use the Maven installation configured in Jenkins
        maven 'Maven 3.9.7' // This should match the name given in Global Tool Configuration
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/ap024982/sampleapp.git'
            }
        }

        stage('Build') {
            steps {
                script {
                    def mvnHome = tool name: 'Maven 3.9.7', type: 'maven'
                    sh "${mvnHome}/bin/mvn clean install"
                }
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    def mvnHome = tool name: 'Maven 3.9.7', type: 'maven'
                    sh "${mvnHome}/bin/mvn test"
                }
            }
        }
    }

    post {
        always {
            junit 'target/surefire-reports/*.xml' // Adjust the path to your test reports
        }
    }
}
